import { readdirSync, statSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, dirname, extname } from 'node:path';
import { log } from '../ui';

const PAGE_EXTENSIONS = new Set(['.ts', '.tsx', '.vue', '.js', '.jsx']);

function walkPages(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const results: string[] = [];

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...walkPages(full));
    } else if (PAGE_EXTENSIONS.has(extname(entry))) {
      results.push(full);
    }
  }

  return results;
}

function toComponentName(filePath: string, pagesDir: string): string {
  const rel = relative(pagesDir, filePath);
  const withoutExt = rel.replace(/\.[^./\\]+$/, '');
  return withoutExt.replace(/\\/g, '/');
}

export async function generateBridgeTypes(
  cwd: string,
  pagesRelDir: string,
  outRelFile: string,
): Promise<void> {
  const pagesDir = join(cwd, pagesRelDir);
  const outFile = join(cwd, outRelFile);

  const files = walkPages(pagesDir);
  const componentNames = files.map((f) => toComponentName(f, pagesDir)).sort();

  if (componentNames.length === 0) {
    log.info(`No page components found in ${pagesRelDir}`);
    return;
  }

  const lines: string[] = [
    '// Auto-generated by faber bridge:types — do not edit manually',
    '// To add typed props, create resources/types/bridge.ts and extend BridgePages.',
    '',
    'export type BridgePages = {',
    ...componentNames.map((name) => `  '${name}': Record<string, unknown>;`),
    '};',
    '',
    'export type BridgePageProps<T extends keyof BridgePages = keyof BridgePages> = BridgePages[T] & {',
    '  errors: Record<string, string>;',
    '  flash: { success?: string; error?: string };',
    '};',
    '',
  ];

  const outDir = dirname(outFile);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  writeFileSync(outFile, lines.join('\n'), 'utf-8');
  log.created(outRelFile);
  log.info(`Generated ${componentNames.length} page type(s)`);
}
